### PR TITLE
90% Create distribution

### PR DESCRIPTION
**Pull request by danielmatthew**

### CODE REVIEW

**Comment by danielmatthew** [comment]
@pads Is this what you were after?

**Comment by pads** [comment]
Yup! How are you generating the CSS, via the rake task? I'll try out this branch and see if it's better than what I have locally.

**Comment by pads** [comment]
Works perfectly - thank you!

**Comment by danielmatthew** [comment]
@pads I, err, just ran 
```bash
sass app.scss /dist/app.css 
sass app.scss /dist/app.min.css --style compressed
```

👀

**Pull request merged**
