### PR TITLE
Update _forms.scss

### PR DESCRIPTION
**Pull request by danielmatthew**
Introduces a `.form-actions` modifier to apply to a `.form-group` in order to group and highlight the final row of a form.

screen shot 2016-10-18 at 16 25 12

For example:

```html
<form class="form-horizontal">
  <div class="form-group form-actions">
    <div class="col-sm-10 col-sm-offset-2">
      <button class="btn btn-default" type="submit">Sign in</button>
    </div>
  </div>
</form>
```

### CODE REVIEW

**Comment by rsinger** [comment]
This looks right to me: 👍

**Comment by rsinger** [comment]
Scratch that, I'm not getting what looks to be the same output:

institution_settings

**Comment by rsinger** [comment]
When I added `padding: 12px` (i.e., the same as wells) to `.form-actions`, it looks more like your example:

institution_settings

**Comment by danielmatthew** [comment]
Oh, fucking bollocks.

Yes. Had that applied in dev tools but didn't copy it into the editor.

**Comment by rsinger** [comment]
MERGE THIS MOFO

**Pull request merged**
